apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-dev
  labels:
    app: flask-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-dev
  template:
    metadata:
      labels:
        app: flask-dev
    spec:
      containers:
        - name: flask-container
          image: flaskapp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "Dev"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
