apiVersion: v1
kind: Service
metadata:
  name: flask-dev-service
spec:
  selector:
    app: flask-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      NodePort: 30081
  type: NodePort
