apiVersion: v1
kind: Service
metadata:
  name: flask-prod-service
spec:
  selector:
    app: flask-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30082
  type: NodePort
